### ISSUE TITLE
patterns in urls.py is deprecated (removed in django 2.0 I think)

### ISSUE THREAD

**Issue by km-pg** [rdegges/django-twilio#132]

**Comment by km-pg** [comment]
After looking into this, I guess test_project/urls.py isn't even used. The settings file directly references test_project.test_app.urls and bypasses test_project/urls.py. I wonder if that file is even needed.

**Comment by km-pg** [comment]
One side effect of skipping the main urls.py file is that you can't use the admin in the test project. That would be nice to use.

**Comment by jheld** [comment]
Hey @km-pg thanks for pointing this out. Yeah, definitely not something we want to hold onto. And since we're 1.8+, we won't need to either. And you're right, the test project does directly look at the app's urls, and yes, having admin access would be great from the test project.

I'll see if it's easy enough for us to simply use the test_project's URLconf (after changing the patterns to be the modern replacement).

**Comment by jheld** [comment]
@km-pg please let me know if you encounter any further issues (based on the `master` branch, not released to PyPI yet). Closing for now.
