### ISSUE TITLE
ProgrammingError: relation "django_twilio_credential" does not exist

### ISSUE THREAD

**Issue by synic** [rdegges/django-twilio#77]
Using django 1.7.1, and django_twilio 0.8.0, when trying to delete a user account, we get the message you see in the subject.  django_twilio is in our INSTALLED_APPS.

```
$ django-admin migrate django_twilio
...
django.db.utils.ProgrammingError: relation "django_twilio_caller" already exist
```

It appears as though the `Credential` was added later, but a proper migration wasn't added to bring it up to speed (I could be wrong about that) :)

**Comment by hwkns** [comment]
Finally tracked this one down.  Way back in https://github.com/rdegges/django-twilio/commit/53693789575b1786afca52fe1b15047e8e07207d, instead of doing the proper thing and creating a second migration, the initial migration was updated.  The old version didn't contain the `Credential` model, so if you had already run the initial migration before this change, you never created the `django_twilio_credential` table in your database.

Here's what you can do to fix it:
- create an empty table in your database named `django_twilio_credential` (so that the next step doesn't fail)
- `manage.py migrate django_twilio zero`
- `manage.py migrate django_twilio`

**Comment by jheld** [comment]
Looks like we're way past the date here. I'll consider adding this to the docs retroactively, but given how long ago this was, I'm more inclined to just let this die.

If you have strong opinions, please re-open and we can discuss.
