### ISSUE TITLE
GET as opposed to POST

### ISSUE THREAD

**Issue by birdsarah** [rdegges/django-twilio#83]
Hi,

(apologies if this is documented somewhere, i did try looking).

I am just experimenting with twilio and django-twilio for the first time.  I was getting 403 when I tried to use a GET rather than a POST from twilio (this is a dropdown option in their UI). 

When using POST, all is well.

Is there anything I should know here. I'm happy to do a small PR to the docs if GET is not supported.

Best,

Bird

**Comment by jheld** [comment]
HI @birdsarah . I know it's been 2.5 years since you opened this issue, but hey, I'd like to see what we can do.

Is this something that was fixed?

The unit tests do allow POST and GET for text sending, but I'm interested to find out what you were looking to do/fix. If you remember, that is!

Thanks!

**Comment by birdsarah** [comment]
Hi! I'm afraid I really don't recall at this point. Suggest we close!
