### ISSUE TITLE
Support twilio 6.x

### ISSUE THREAD

**Issue by binhe16** [rdegges/django-twilio#96]
Got this deprecation notice from Twilio: 
The old library (5.x) will be officially supported until 7/3/2017. After that day, Twilio will stop providing bug fixes and Support might ask you to upgrade before debugging issues.

**Comment by yousifa** [comment]
+1

**Comment by jheld** [comment]
+1

**Comment by jheld** [comment]
@rdegges so it is now in master. What are the next steps before an official PyPI update? Do you need help? My team will be testing soon but we're curious for your thoughts.

**Comment by hwkns** [comment]
It's almost a month since 7/3...  Any word on this?

**Comment by jheld** [comment]
We installed the master build back then and we've had no issues. Are there concerns on specific features/support?

**Comment by mulka** [comment]
I've pushed a forked version of django-twilio to pypi as django-twilio2 which supports the twilio library 6.x. Check it out!

**Comment by hwkns** [comment]
@rdegges are you still maintaining this project, or should we switch to the package @mulka published?

**Comment by rdegges** [comment]
Hey! I mentioned this in multiple comment threads on here, but no. I have not maintained this library for a while. I've been actively seeking maintainers, and I've been wanting to pass over ownership. I told people that if they'd like to contribute I'll happily give them admin access to the Github repo and PyPI package.

I offered to @mulka but haven't heard back yet. I know that as a user it's annoying to have forks that end in numbers, so I'd like to avoid that out of pure convenience if possible!

The offer still totally stands: if any of you would like to contribute and help out please let me know so I can add you as an owner!

**Comment by jheld** [comment]
Please check out the latest alpha build on PyPI or build it from master.

**Comment by jheld** [comment]
Hey everyone.

I've released version `0.9.0` to [PyPI](https://pypi.python.org/pypi/django-twilio/0.9.0). It is nearly identical to `0.9.0a1` (docs, some test case and module import improvements). My company has been using it for a week and so far we've encountered no issues. I'll update via an issue and MR if we do find anything.

Because this project is not yet `1.0`, and because the fixes going into `0.9.0` have been tested in various forms over the last half year (and been in use on `django-twilio2`), I decided not to have `beta` or `release candidate` releases. I know you and other API users have been wanting this project to continue to work well.

In the future, I anticipate that we'll design a workflow and cadence for releases. Once we hit `1.0.0`, that will be a high priority.

Please upgrade :) As usual, please open any issues as you see them, and if able, any MRs.

As such, I'm closing this issue. We can re-open it, but if possible, it would be nice to have a new one with any specific issues that are encountered (if any).
